#pragma once

#include "DtCarFunction.h"

/** GateSpec.ini + reserved tab (DtSpecSettings.rc). All channels share global [limits]. */
class CDtSpecDlg : public CDialogEx
{
public:
	explicit CDtSpecDlg(DtCarFunction* pFn, CWnd* pParent = NULL);

	enum { IDD = IDD_DIALOG_SPEC };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);
	virtual BOOL OnInitDialog();
	virtual BOOL PreTranslateMessage(MSG* pMsg);
	virtual void OnOK();
	afx_msg BOOL OnEraseBkgnd(CDC* pDC);
	afx_msg void OnTcnSelchangeTabSpec(NMHDR* pNMHDR, LRESULT* pResult);
	afx_msg void OnBnClickedBtnBpBrowse();
	afx_msg void OnBnClickedBpSave();
	afx_msg void OnBnClickedRadBpNeighbor();
	afx_msg void OnBnClickedRadBpHuawei();
	afx_msg void OnBnClickedChkFwEn();

	DECLARE_MESSAGE_MAP()

	DtCarFunction* m_pFn;

	CFont m_fontTitle;
	CFont m_fontBody;
	CFont m_fontSmall;

	CTabCtrl m_tab;
	CStatic m_stTitle;
	CStatic m_stPath;
	CStatic m_stHint;
	CStatic m_stFormula;
	CButton m_grpTiming;
	CButton m_grpLimits;
	CButton m_grpTempI2c;
	CButton m_grpBadPixel;
	CButton m_chkBpEn;
	CStatic m_lblBpAlgo;
	CButton m_radBpNeighbor;
	CButton m_radBpHuawei;
	CButton m_grpBpHuawei;
	CButton m_grpBpNeighbor;
	CStatic m_lblBpClusterTh;
	CEdit m_edBpClusterTh;
	CStatic m_lblBpClusterMin;
	CEdit m_edBpClusterMin;
	CStatic m_lblBpSinglePpm;
	CEdit m_edBpSinglePpm;
	CButton m_chkBpGrGbToG;
	CStatic m_lblBpMax;
	CStatic m_lblBpHotDelta;
	CStatic m_lblBpHotAbs;
	CStatic m_lblBpBorder;
	CEdit m_edBpMax;
	CEdit m_edBpHotDelta;
	CEdit m_edBpHotAbs;
	CEdit m_edBpBorder;
	CButton m_chkBpSave;
	CButton m_grpBpSnapFiles;
	CButton m_chkBpSaveBmp;
	CButton m_chkBpSavePacked;
	CButton m_chkBpSaveU12;
	CButton m_chkBpSaveU10;
	CStatic m_lblBpDir;
	CEdit m_edBpDir;
	CButton m_btnBpBrowse;
	CStatic m_stBpHint;
	CButton m_grpFirmware;
	CButton m_chkFwEn;
	CStatic m_lblFwFov;
	CComboBox m_cmbFwFov;
	CStatic m_lblFwWarmup;
	CEdit m_edFwWarmup;
	CStatic m_lblFwPath;
	CStatic m_stFwPath;
	CStatic m_lblFwGrabIni;
	CEdit m_edFwGrabIni;
	CButton m_btnFwGrabBrowse;
	CStatic m_stFwHint;
	CStatic m_lblDelay;
	CEdit m_edDelay;
	CStatic m_lblDef1;
	CStatic m_lblDef2;
	CStatic m_lblDef3;
	CStatic m_lblDef4;
	CStatic m_lblDef5;
	CStatic m_lblDef6;
	CEdit m_edDefMinSsr;
	CEdit m_edDefMaxSsr;
	CEdit m_edDefMinCur;
	CEdit m_edDefMaxCur;
	CEdit m_edDefMinTemp;
	CEdit m_edDefMaxTemp;
	CButton m_chkTempEn;
	CStatic m_lblTempAddr;
	CStatic m_lblTempMode;
	CStatic m_lblTempRegLo;
	CStatic m_lblTempRegHi;
	CStatic m_lblTempCoeffLo;
	CStatic m_lblTempCoeffHi;
	CStatic m_lblTempDiv;
	CStatic m_lblTempOffset;
	CEdit m_edTempAddr;
	CEdit m_edTempMode;
	CEdit m_edTempRegLo;
	CEdit m_edTempRegHi;
	CEdit m_edTempCoeffLo;
	CEdit m_edTempCoeffHi;
	CEdit m_edTempDiv;
	CEdit m_edTempOffset;

	GateChannelLimits m_def;
	GateSensorTempI2c m_tempI2c;
	GateBadPixelDarkCfg m_badPixel;
	GateFirmwareBurnCfg m_firmware;
	GateAgingTestCfg m_agingTest;
	GateOvenCfg m_oven;
	GateAgingGateCfg m_agingGate;
	GateAgingVoltageI2cCfg m_agingVoltage;

	CButton m_grpAging;
	CButton m_chkAgingEn;
	CButton m_chkAgingHeatStart;
	CButton m_grpOven;
	CStatic m_lblOvenProfile;
	CComboBox m_cmbOvenProfile;
	CStatic m_lblOvenHeatMode;
	CComboBox m_cmbOvenHeatMode;
	CStatic m_lblOvenHost;
	CEdit m_edOvenHost;
	CStatic m_lblOvenPort;
	CEdit m_edOvenPort;
	CStatic m_lblOvenUnit;
	CEdit m_edOvenUnit;
	CStatic m_lblOvenTarget;
	CEdit m_edOvenTarget;
	CStatic m_lblOvenTol;
	CEdit m_edOvenTol;
	CStatic m_lblOvenWait;
	CEdit m_edOvenWait;
	CStatic m_lblOvenPoll;
	CEdit m_edOvenPoll;
	CButton m_chkOvenDual;
	CStatic m_lblOvenDPv;
	CEdit m_edOvenDPv;
	CButton m_chkOvenCooldown;
	CStatic m_lblOvenCooldownTarget;
	CEdit m_edOvenCooldownTarget;
	CStatic m_lblOvenCooldownTimeout;
	CEdit m_edOvenCooldownTimeout;
	CStatic m_lblOvenCooldownTol;
	CEdit m_edOvenCooldownTol;
	CButton m_grpAgingGate;
	CStatic m_lblAgingDur;
	CEdit m_edAgingDur;
	CStatic m_lblAgingSample;
	CEdit m_edAgingSample;
	CStatic m_lblAgingMinSsr;
	CEdit m_edAgingMinSsr;
	CStatic m_lblAgingMaxSsr;
	CEdit m_edAgingMaxSsr;
	CStatic m_lblAgingMinCur;
	CEdit m_edAgingMinCur;
	CStatic m_lblAgingMaxCur;
	CEdit m_edAgingMaxCur;
	CStatic m_lblAgingMinTemp;
	CEdit m_edAgingMinTemp;
	CStatic m_lblAgingMaxTemp;
	CEdit m_edAgingMaxTemp;
	CStatic m_lblAgingMinAvdd;
	CEdit m_edAgingMinAvdd;
	CStatic m_lblAgingMaxAvdd;
	CEdit m_edAgingMaxAvdd;
	CStatic m_lblAgingMinIovdd;
	CEdit m_edAgingMinIovdd;
	CStatic m_lblAgingMaxIovdd;
	CEdit m_edAgingMaxIovdd;
	CStatic m_lblAgingMinDvdd;
	CEdit m_edAgingMinDvdd;
	CStatic m_lblAgingMaxDvdd;
	CEdit m_edAgingMaxDvdd;
	CButton m_grpAgingVolt;
	CButton m_chkAgingVoltEn;
	CStatic m_lblAgingVoltMode;
	CEdit m_edAgingVoltMode;
	CStatic m_lblAgingVoltScale;
	CEdit m_edAgingVoltScale;
	CStatic m_lblAgingRegAvdd;
	CEdit m_edAgingRegAvdd;
	CStatic m_lblAgingRegAvddH;
	CEdit m_edAgingRegAvddH;
	CStatic m_lblAgingRegIovdd;
	CEdit m_edAgingRegIovdd;
	CStatic m_lblAgingRegIovddH;
	CEdit m_edAgingRegIovddH;
	CStatic m_lblAgingRegDvdd;
	CEdit m_edAgingRegDvdd;
	CStatic m_lblAgingRegDvddH;
	CEdit m_edAgingRegDvddH;
	CButton m_grpOvenAdv;
	CStatic m_lblOvenRegSet;
	CEdit m_edOvenRegSet;
	CStatic m_lblOvenCoilStart;
	CEdit m_edOvenCoilStart;
	CStatic m_lblOvenCoilStop;
	CEdit m_edOvenCoilStop;
	CStatic m_lblOvenRegPv;
	CEdit m_edOvenRegPv;
	CStatic m_lblOvenRegRun;
	CEdit m_edOvenRegRun;
	CStatic m_lblOvenRunBit;
	CEdit m_edOvenRunBit;
	CStatic m_lblOvenRegFault;
	CEdit m_edOvenRegFault;
	CButton m_btnOvenTest;
	CButton m_btnOvenReadPv;
	CButton m_btnOvenSetTemp;
	CButton m_btnOvenStart;
	CButton m_btnOvenStop;
	CStatic m_stAgingHint;

	int m_specActivePage;
	bool m_specFrameReady;
	double m_specLayoutScale;
	int m_specMargin;
	int m_specTabH;
	int m_specBtnBandH;
	int m_specBtnH;
	int m_specBtnW;
	int m_specScrollPos;
	int m_specContentH;
	int m_specContentHByPage[4];
	int m_specVisibleContentH;

	void ApplyDialogFonts();
	void EnsureStandardCheckAndRadioButtons();
	void ResizeSpecClient(int clientW, int clientH);
	void ClampSpecDialogToWorkArea(const CRect& workArea);
	int MaxClientHeightForWorkArea(int clientW, const CRect& workArea, double scale) const;
	void PlaceSpecTabAndButtons(const CRect& cr);
	void ShowSpecPage(int page);
	void UpdateFormulaText();
	/** Once per open/DPI: scale, margins, measure all pages. */
	void InitSpecDialogFrame(bool force);
	/** Tab switch: resize client to fit active page (aging tab uses full height). */
	void ResizeSpecDialogForActivePage();
	/** Tab switch: layout active page only. */
	void RelayoutSpecPage();
	void AdjustSpecPageZOrder();
	void RaiseSpecDialogButtons();
	void HideGatePageControls();
	void HideBadPixelPageControls();
	void HideFirmwarePageControls();
	void HideAgingPageControls();
	void HideAllSpecPageControls();
	void ClipActiveSpecPageControls(int visTop, int visBottom);
	void ApplySpecScroll(int newPos);
	int SpecChromeHeightPx(double scale) const;
	double GetSpecUiScale() const;
	int MeasureAllPageHeights(const CRect& viewport, double scale, int outHeights[4]);
	void UpdateSpecScrollForActivePage();
	int ActivePageContentH() const;
	int SpecPageMaxControlBottom(int page);
	void SyncSpecScrollHeightFromControls(int contentTop);
	int MeasureMaxPageHeight(const CRect& viewport, double scale);
	int LayoutGatePage(const CRect& viewport, double scale, bool bShow);
	int LayoutBadPixelPage(const CRect& viewport, double scale, bool bShow);
	int LayoutFirmwarePage(const CRect& viewport, double scale, bool bShow);
	int LayoutAgingPage(const CRect& viewport, double scale, bool bShow);
	void FillOvenProfileCombo();
	void FillOvenHeatModeCombo();
	void ApplyOvenProfileToUi(OvenProfileId profile);
	void UpdateOvenRegEditEnableState();
	void ReadOvenFromUi(GateOvenCfg* out);
	GateOvenCfg BuildOvenCfgFromUi() const;
	afx_msg void OnCbnSelchangeOvenProfile();
	afx_msg void OnBnClickedOvenTest();
	afx_msg void OnBnClickedOvenReadPv();
	afx_msg void OnBnClickedOvenSetTemp();
	afx_msg void OnBnClickedOvenStart();
	afx_msg void OnBnClickedOvenStop();
	void FillFirmwareFovCombo();
	void UpdateFirmwarePathLabel();
	afx_msg void OnBnClickedBtnFwGrabBrowse();
	afx_msg void OnCbnSelchangeFwFov();
	afx_msg LRESULT OnDpiChanged(WPARAM wParam, LPARAM lParam);
	afx_msg void OnVScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar);
	afx_msg BOOL OnMouseWheel(UINT nFlags, short zDelta, CPoint pt);
	void UpdateBadPixelLabels();
	void UpdateBadPixelAlgoUi();
	void UpdateBadPixelSnapTypeUi();
	void SetBadPixelAlgoMode(int algoMode);
	void RaiseBadPixelAlgoControls();
};

