//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DtSample.rc
//
#define VER_B                           0
#define VER_A                           1
#define VER_C                           1
#define VER_D                           8
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DTSAMPLE_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_OSTEST               130
#define IDR_MENU1                       132
#define IDD_IICDEBUG_DIALOG             134
#define IDD_DIALOG_SPEC                 135
#define IDC_COMBO_DEV                   1000
#define IDC_BUTTON_ENUM                 1001
#define IDC_BUTTON_LOAD                 1002
#define IDC_BUTTON_START                1003
#define IDC_BUTTON_OPEN                 1004
#define IDC_EDIT_STATUS                 1005
#define IDC_BUTTON_EDIT                 1005
#define IDC_VIDEO                       1006
#define IDC_EDIT_MSG2                   1007
#define IDC_SETPOWER                    1008
#define IDC_SETMCLK                     1009
#define IDC_EDITAVDD                    1010
#define IDC_EDITDOVDD                   1011
#define IDC_EDITDVDD                    1012
#define IDC_EDITAFVCC                   1013
#define IDC_EDITVPP                     1014
#define IDC_EDIT_INI                    1015
#define IDC_EDITMCLK                    1016
#define IDC_INTERLNEL                   1017
#define IDC_CHECK_DISPLAYEN             1018
#define IDC_EDITDOVDD2                  1019
#define IDC_EDIT_REGNUM                 1019
#define IDC_CAP                         1020
#define IDC_CHECK_STATUS                1020
#define IDC_COMBO_TESTMODE              1021
#define IDC_CHECK_STATUS2               1021
#define IDC_CHECK_OSTEST                1021
#define IDC_COMBO_FORMAT                1022
#define IDC_COMBO_PORT                  1023
#define IDC_EDIT_OISVDD                 1024
#define IDC_EDIT_AVDD2                  1025
#define IDC_EDIT1                       1026
#define IDC_EDIT_LANECNT                1026
#define IDC_ADDRESS_EDIT                1026
#define IDC_H_EDIT                      1026
#define IDC_BUTTON_I2CBUS               1027
#define IDC_REGISTER_EDIT               1027
#define IDC_BUTTON1                     1028
#define IDC_BUTTON_PMUOFF               1028
#define IDC_BUTTON_OSTEST               1028
#define IDC_COMBO_FORMAT2               1028
#define IDC_COMBO_TW                    1028
#define IDC_SEARCH_BUTTON               1028
#define IDC_EDIT_AVDD_HWSTB             1029
#define IDC_VALUE_EDIT                  1029
#define IDC_EDIT_DOVDD_HWSTB            1030
#define IDC_EDIT_DVDD_HWSTB             1031
#define IDC_EDIT_AFVCC_HWSTB            1032
#define IDC_EDIT_VPP_HWSTB              1033
#define IDC_LIST4                       1033
#define IDC_EDIT_OISVDD_HWSTB           1034
#define IDC_COMBO_I2CMODE               1036
#define IDC_EDIT_AVDD2_HWSTB            1038
#define IDC_EDIT_SLAVEADDR              1041
#define IDC_EDIT_REG                    1042
#define IDC_EDIT_VALUE                  1043
#define IDC_BUTTON_WRITE                1044
#define IDC_BUTTON3                     1045
#define IDC_BUTTON_READ                 1045
#define IDC_Read                        1045
#define IDC_BUTTON_SPEC                 1071
#define IDC_BUTTON_CHANNEL              1072
#define IDD_DIALOG_CHANNEL              136
#define IDC_TREE_CHANNEL                2205
#define IDC_BTN_CH_ALL                  2206
#define IDC_BTN_CH_NONE                 2207
#define IDC_STATIC_CH_HINT              2208
#define IDC_STATIC_CH_GROUP             2209
#define IDC_STATIC_CH_STATUS            2210
#define IDC_CHECK1                      1046
#define IDC_LOOP_DISPLAY                1046
#define IDC_EDIT_VC_FR_DLY              1047
#define IDC_EDIT_SAMPLE_H               1048
#define IDC_EDIT_SAMPLE_V               1049
#define IDC_CHECK_SAMPLE_EN             1050
#define IDC_EDIT_FRAME_RATE             1051
#define IDC_Write                       1057
#define IDC_Dump                        1058
#define IDC_SlaveID                     1059
#define IDC_Addres                      1060
#define IDC_Address                     1060
#define IDC_EDIT_Val                    1061
#define IDC_EDIT_Mode                   1062
#define IDC_EDIT_DevID                  1064
#define IDC_READ_BUTTON                 1065
#define IDC_WRITE_BUTTON                1066
#define IDC_I2C_MODE_COMBO              1067
#define IDC_TakePixel_CHECK             1068
#define IDC_V_EDIT                      1069
#define IDC_STATIC_SPEC_PATH            2100
#define IDC_EDIT_SPEC_DELAY             2101
#define IDC_EDIT_SPEC_DEF_MINSSR        2102
#define IDC_EDIT_SPEC_DEF_MAXSSR        2103
#define IDC_EDIT_SPEC_DEF_MINCUR        2104
#define IDC_EDIT_SPEC_DEF_MAXCUR        2105
#define IDC_COMBO_SPEC_CHANNEL          2106
#define IDC_EDIT_SPEC_CH_MINSSR         2107
#define IDC_EDIT_SPEC_CH_MAXSSR         2108
#define IDC_EDIT_SPEC_CH_MINCUR         2109
#define IDC_EDIT_SPEC_CH_MAXCUR         2110
#define IDC_TAB_SPEC                    2130
#define IDC_GRP_SPEC_TIMING             2131
#define IDC_GRP_SPEC_LIMITS             2132
#define IDC_GRP_SPEC_CHANNEL            2133
#define IDC_STATIC_SPEC_TITLE           2134
#define IDC_STATIC_SPEC_HINT            2135
#define IDC_LBL_SPEC_DELAY              2136
#define IDC_LBL_DEF1                    2137
#define IDC_LBL_DEF2                    2138
#define IDC_LBL_DEF3                    2139
#define IDC_LBL_DEF4                    2140
#define IDC_LBL_CH0                     2141
#define IDC_LBL_CH1                     2142
#define IDC_LBL_CH2                     2143
#define IDC_LBL_CH3                     2144
#define IDC_LBL_CH4                     2145
#define IDC_GRP_RESERVED                2146
#define IDC_STATIC_RESERVED_BODY        2147
#define IDC_LBL_DEF5                    2148
#define IDC_LBL_DEF6                    2149
#define IDC_EDIT_SPEC_DEF_MINTEMP       2150
#define IDC_EDIT_SPEC_DEF_MAXTEMP       2151
#define IDC_GRP_SPEC_TEMP_I2C           2152
#define IDC_CHK_SPEC_TEMP_EN            2153
#define IDC_LBL_TEMP_ADDR               2154
#define IDC_EDIT_SPEC_TEMP_ADDR         2155
#define IDC_LBL_TEMP_MODE               2156
#define IDC_EDIT_SPEC_TEMP_MODE         2157
#define IDC_LBL_TEMP_REGLO              2158
#define IDC_EDIT_SPEC_TEMP_REGLO        2159
#define IDC_LBL_TEMP_REGHI              2160
#define IDC_EDIT_SPEC_TEMP_REGHI        2161
#define IDC_LBL_TEMP_COEFFLO            2162
#define IDC_EDIT_SPEC_TEMP_COEFFLO      2163
#define IDC_LBL_TEMP_COEFFHI            2164
#define IDC_EDIT_SPEC_TEMP_COEFFHI      2165
#define IDC_LBL_TEMP_DIV                2166
#define IDC_EDIT_SPEC_TEMP_DIV          2167
#define IDC_LBL_TEMP_OFFSET             2168
#define IDC_EDIT_SPEC_TEMP_OFFSET       2169
#define IDC_STATIC_SPEC_FORMULA         2170
#define IDC_GRP_SPEC_BADPIXEL           2171
#define IDC_CHK_SPEC_BP_EN              2172
#define IDC_LBL_BP_MAX                  2173
#define IDC_EDIT_SPEC_BP_MAX            2174
#define IDC_LBL_BP_HOTDELTA             2175
#define IDC_EDIT_SPEC_BP_HOTDELTA       2176
#define IDC_LBL_BP_HOTABS               2177
#define IDC_EDIT_SPEC_BP_HOTABS         2178
#define IDC_LBL_BP_BORDER               2179
#define IDC_EDIT_SPEC_BP_BORDER         2180
#define IDC_CHK_SPEC_BP_SAVE            2181
#define IDC_STATIC_SPEC_BP_HINT         2182
#define IDC_GRP_RESERVED2               2183
#define IDC_STATIC_RESERVED2_BODY       2184
#define IDC_CHK_SPEC_FW_EN              2205
#define IDC_LBL_SPEC_FW_FOV             2206
#define IDC_COMBO_SPEC_FW_FOV           2213
#define IDC_LBL_SPEC_FW_WARMUP          2208
#define IDC_EDIT_SPEC_FW_WARMUP         2209
#define IDC_LBL_SPEC_FW_PATH            2210
#define IDC_STATIC_SPEC_FW_PATH         2211
#define IDC_STATIC_SPEC_FW_HINT         2212
#define IDC_LBL_SPEC_FW_GRAB_INI        2214
#define IDC_EDIT_SPEC_FW_GRAB_INI       2215
#define IDC_BTN_SPEC_FW_GRAB_BROWSE     2216
#define IDC_LBL_BP_DIR                    2185
#define IDC_EDIT_SPEC_BP_DIR              2186
#define IDC_BTN_SPEC_BP_BROWSE            2187
#define IDC_LBL_BP_ALGO                   2188
#define IDC_RAD_BP_ALGO_NEIGHBOR          2189
#define IDC_RAD_BP_ALGO_HUAWEI            2190
#define IDC_GRP_BP_HUAWEI                 2191
#define IDC_LBL_BP_CLUSTER_TH             2192
#define IDC_EDIT_SPEC_BP_CLUSTER_TH       2193
#define IDC_LBL_BP_CLUSTER_MIN            2194
#define IDC_EDIT_SPEC_BP_CLUSTER_MIN      2195
#define IDC_LBL_BP_SINGLE_PPM             2196
#define IDC_EDIT_SPEC_BP_SINGLE_PPM       2197
#define IDC_CHK_SPEC_BP_GRGBTOG           2198
#define IDC_GRP_BP_NEIGHBOR               2199
#define IDC_GRP_BP_SNAP_FILES             2200
#define IDC_CHK_SPEC_BP_SAVE_BMP          2201
#define IDC_CHK_SPEC_BP_SAVE_PACKED       2202
#define IDC_CHK_SPEC_BP_SAVE_U12          2203
#define IDC_CHK_SPEC_BP_SAVE_U10          2204
#define IDC_VIDEO0                      2000
#define IDC_VIDEO1                      2001
#define IDC_VIDEO2                      2002
#define IDC_VIDEO3                      2003
#define IDC_VIDEO4                      2004
#define IDC_VIDEO5                      2005
#define IDC_VIDEO6                      2006
#define IDC_VIDEO7                      2007
#define IDC_VIDEO8                      2008
#define IDC_VIDEO9                      2009
#define IDC_VIDEO10                     2010
#define IDC_VIDEO11                     2011
#define IDC_VIDEO12                     2012
#define IDC_VIDEO13                     2013
#define IDC_VIDEO14                     2014
#define IDC_VIDEO15                     2015
#define IDC_VIDEO16                     2016
#define IDC_VIDEO17                     2017
#define IDC_VIDEO18                     2018
#define IDC_VIDEO19                     2019
#define IDC_VIDEO20                     2020
#define IDC_VIDEO21                     2021
#define IDC_VIDEO22                     2022
#define IDC_VIDEO23                     2023
#define IDC_VIDEO24                     2024
#define IDC_VIDEO25                     2025
#define IDC_VIDEO26                     2026
#define IDC_VIDEO27                     2027
#define IDC_VIDEO28                     2028
#define IDC_VIDEO29                     2029
#define IDC_VIDEO30                     2030
#define IDC_VIDEO31                     2031
#define IDC_TAB_FA132                   2217
#define IDC_STATIC_FA132_OVERVIEW       2218
#define IDC_MES_BAR                     2219
#define IDC_MES_WORK_ORDER              2220
#define IDC_MES_BOARD0                  2221
#define IDC_MES_BOARD1                  2222
#define IDC_MES_BOARD2                  2223
#define IDC_MES_BOARD3                  2224
#define IDC_MES_BOUND_LABEL             2225
#define IDC_MES_LBL_WORK_ORDER          2226
#define IDC_MES_WO_LOCK                 2227
#define IDC_MES_WO_LOCKED               2228
#define IDC_GRP_SPEC_AGING              2229
#define IDC_CHK_SPEC_AGING_EN           2230
#define IDC_CHK_SPEC_AGING_HEAT_START   2231
#define IDC_GRP_SPEC_OVEN               2232
#define IDC_LBL_SPEC_OVEN_PROFILE       2233
#define IDC_COMBO_SPEC_OVEN_PROFILE     2234
#define IDC_LBL_SPEC_OVEN_HOST          2235
#define IDC_EDIT_SPEC_OVEN_HOST         2236
#define IDC_LBL_SPEC_OVEN_PORT          2237
#define IDC_EDIT_SPEC_OVEN_PORT         2238
#define IDC_LBL_SPEC_OVEN_UNIT          2239
#define IDC_EDIT_SPEC_OVEN_UNIT         2240
#define IDC_LBL_SPEC_OVEN_TARGET        2241
#define IDC_EDIT_SPEC_OVEN_TARGET       2242
#define IDC_LBL_SPEC_OVEN_TOL           2243
#define IDC_EDIT_SPEC_OVEN_TOL          2244
#define IDC_LBL_SPEC_OVEN_WAIT          2245
#define IDC_EDIT_SPEC_OVEN_WAIT         2246
#define IDC_LBL_SPEC_OVEN_POLL          2247
#define IDC_EDIT_SPEC_OVEN_POLL         2248
#define IDC_GRP_SPEC_AGING_GATE         2249
#define IDC_LBL_SPEC_AGING_DUR          2250
#define IDC_EDIT_SPEC_AGING_DUR         2251
#define IDC_LBL_SPEC_AGING_SAMPLE       2252
#define IDC_EDIT_SPEC_AGING_SAMPLE      2253
#define IDC_LBL_SPEC_AGING_MIN_SSR      2254
#define IDC_EDIT_SPEC_AGING_MIN_SSR     2255
#define IDC_LBL_SPEC_AGING_MAX_SSR      2256
#define IDC_EDIT_SPEC_AGING_MAX_SSR     2257
#define IDC_LBL_SPEC_AGING_MIN_CUR      2258
#define IDC_EDIT_SPEC_AGING_MIN_CUR     2259
#define IDC_LBL_SPEC_AGING_MAX_CUR      2260
#define IDC_EDIT_SPEC_AGING_MAX_CUR     2261
#define IDC_LBL_SPEC_AGING_MIN_TEMP     2262
#define IDC_EDIT_SPEC_AGING_MIN_TEMP    2263
#define IDC_LBL_SPEC_AGING_MAX_TEMP     2264
#define IDC_EDIT_SPEC_AGING_MAX_TEMP    2265
#define IDC_GRP_SPEC_OVEN_ADV           2266
#define IDC_LBL_SPEC_OVEN_REG_SET       2267
#define IDC_EDIT_SPEC_OVEN_REG_SET      2268
#define IDC_LBL_SPEC_OVEN_COIL_START    2269
#define IDC_EDIT_SPEC_OVEN_COIL_START   2270
#define IDC_LBL_SPEC_OVEN_COIL_STOP     2271
#define IDC_EDIT_SPEC_OVEN_COIL_STOP    2272
#define IDC_LBL_SPEC_OVEN_REG_PV        2273
#define IDC_EDIT_SPEC_OVEN_REG_PV       2274
#define IDC_LBL_SPEC_OVEN_REG_RUN       2275
#define IDC_EDIT_SPEC_OVEN_REG_RUN      2276
#define IDC_LBL_SPEC_OVEN_RUN_BIT       2286
#define IDC_EDIT_SPEC_OVEN_RUN_BIT      2287
#define IDC_LBL_SPEC_OVEN_REG_FAULT     2288
#define IDC_EDIT_SPEC_OVEN_REG_FAULT    2289
#define IDC_BTN_SPEC_OVEN_TEST          2277
#define IDC_BTN_SPEC_OVEN_READ_PV       2278
#define IDC_BTN_SPEC_OVEN_SETTEMP       2279
#define IDC_BTN_SPEC_OVEN_START         2280
#define IDC_BTN_SPEC_OVEN_STOP          2281
#define IDC_STATIC_SPEC_AGING_HINT        2282
#define IDC_CHK_SPEC_OVEN_D_EN          2283
#define IDC_LBL_SPEC_OVEN_D_HOST        2284
#define IDC_EDIT_SPEC_OVEN_D_HOST       2285
#define IDC_LBL_SPEC_OVEN_D_PV          2290
#define IDC_EDIT_SPEC_OVEN_D_REG_PV     2291
#define IDC_CHK_SPEC_OVEN_D_INDEP       2292
#define IDC_LBL_SPEC_OVEN_D_PORT        2293
#define IDC_EDIT_SPEC_OVEN_D_PORT       2294
#define IDC_LBL_SPEC_OVEN_D_UNIT        2295
#define IDC_EDIT_SPEC_OVEN_D_UNIT       2296
#define IDC_LBL_SPEC_OVEN_HEAT_MODE     2297
#define IDC_COMBO_SPEC_OVEN_HEAT_MODE   2298
#define IDC_GRP_SPEC_AGING_VOLT         2299
#define IDC_CHK_SPEC_AGING_VOLT_EN      2300
#define IDC_LBL_SPEC_AGING_VOLT_MODE    2301
#define IDC_EDIT_SPEC_AGING_VOLT_MODE   2302
#define IDC_LBL_SPEC_AGING_VOLT_SCALE   2303
#define IDC_EDIT_SPEC_AGING_VOLT_SCALE  2304
#define IDC_LBL_SPEC_AGING_REG_AVDD     2305
#define IDC_EDIT_SPEC_AGING_REG_AVDD    2306
#define IDC_LBL_SPEC_AGING_REG_IOVDD    2307
#define IDC_EDIT_SPEC_AGING_REG_IOVDD    2308
#define IDC_LBL_SPEC_AGING_REG_DVDD     2309
#define IDC_EDIT_SPEC_AGING_REG_DVDD    2310
#define IDC_LBL_SPEC_AGING_REG_AVDD_H   2323
#define IDC_EDIT_SPEC_AGING_REG_AVDD_H  2324
#define IDC_LBL_SPEC_AGING_REG_IOVDD_H  2325
#define IDC_EDIT_SPEC_AGING_REG_IOVDD_H 2326
#define IDC_LBL_SPEC_AGING_REG_DVDD_H   2327
#define IDC_EDIT_SPEC_AGING_REG_DVDD_H  2328
#define IDC_LBL_SPEC_AGING_MIN_AVDD     2311
#define IDC_EDIT_SPEC_AGING_MIN_AVDD    2312
#define IDC_LBL_SPEC_AGING_MAX_AVDD     2313
#define IDC_EDIT_SPEC_AGING_MAX_AVDD    2314
#define IDC_LBL_SPEC_AGING_MIN_IOVDD    2315
#define IDC_EDIT_SPEC_AGING_MIN_IOVDD   2316
#define IDC_LBL_SPEC_AGING_MAX_IOVDD    2317
#define IDC_EDIT_SPEC_AGING_MAX_IOVDD   2318
#define IDC_LBL_SPEC_AGING_MIN_DVDD     2319
#define IDC_EDIT_SPEC_AGING_MIN_DVDD    2320
#define IDC_LBL_SPEC_AGING_MAX_DVDD     2321
#define IDC_EDIT_SPEC_AGING_MAX_DVDD    2322
#define ID_DEVICE_INTERNALSTATUS        32771
#define ID_DEVICE_START                 32772
#define ID_DEVICE_STOP                  32773
#define ID_DEVICE_HOLD                  32774
#define ID_DEVICE_RETART                32775
#define ID_DEVICE_RESTART               32776
#define ID_DEVICE_INTERNALREGISTER      32777
#define ID_DEVICE_INTERNALDEBUG         32778
#define ID_DEVICE_SAVEPIC               32779
#define ID_DEVICE_I2CDEBUG              32780

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         2323
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
