##全局设置
[global]
enable      =   1;                调试信息使能
all         =   0;                全开
logfile     =   1;                直接记录的dtdbg.log文件中
maxCount    =   20000;           一个文件允许最多的记录数
keep        =   0;                错误和警告信息出现的时候，将最近的调试信息保存到文件，0为关闭，keep记录数
autokeep    =   0;                自动保持使能，使能后，一般信息（info、proc）将不写入文件，而是先保持在内存中，采用循环记录方式；当发生警告和错误时，将触发写入到文件
new         =   0;                新的文件记录方式，用4个文件，滚动记录，可以避免文件个数的增加
remote      =   0;                远端打印信息，如主单片机，电源模块调试信息	
logfilePath = 
##vfvlog模式配置
vfvlog      =   1;                是否启用 vfvlog 模式，该模式下还由“logfile”参数指定是否用文件记录（logfile=1），还是共享内存方式（logfile=0）
vfvFileSize =   67108864;         vfvlog 模式下，配置文件大小  
vfvBufSize  =   16777216;         vfvlog 模式下，配置共享内存大小 
sizechange  =   0；               size change触发产生internal信息记录新的文件和生成波形文件

[device_global]
enable      =   0;                调试信息使能,设备端打印信息对效率有影响
all         =   0;

[remote]
error	      =    1;
warn	      =    1;
info	      =    0;
proc	      =    0;
dump	      =    0;

[device_os]
error	      =    1;
warn	      =    1;
info	      =    0;
proc	      =    0;
dump	      =    0;

[device_i2c]
error	      =    1;
warn	      =    1;
info	      =    1;
proc	      =    0;
dump	      =    0;

[device_spi]
error	      =    1;
warn	      =    1;
info	      =    0;
proc	      =    0;
dump	      =    0;

##调试打印等级
error	      =    1;           错误信息
warn	      =    1;           警告信息
info	      =    1;           提示信息
proc	      =    0;           过程信息，过程信息一般比较大，建议在调试流程性问题的时候开启
dump	      =    1;           直接dump文本信息，不做格式化处理
##link类型主要是底层通讯层，有大量的info和proc信息，默认只要打开error和warn即可
[link]
error	      =    1;
warn	      =    1;
info	      =    0;
proc	      =    0;
dump	      =    0;

[api]
error	      =    1;
warn	      =    1;
info	      =    0;
proc	      =    1;
dump	      =    1;

[enum]
error	      =    1;
warn	      =    1;
info	      =    0;
proc	      =    1;
dump	      =    1;


[os]
error	      =    1;
warn	      =    1;
info	      =    1;
proc	      =    1;
dump	      =    1;

[grab]
error	      =    1;
warn	      =    1;
info	      =    1;
proc	      =    1;
dump	      =    1;

[stream]
error	      =    1;
warn	      =    1;
info	      =    1;
proc	      =    1;
dump	      =    1;

[eeprom]
error	      =    1;
warn	      =    1;
info	      =    1;
proc	      =    0;
dump	      =    1;

[i2c]
error	      =    1;
warn	      =    1;
info	      =    1;
proc	      =    1;
dump	      =    1;

[power]
error	      =    1;
warn	      =    1;
info	      =    1;
proc	      =    1;
dump	      =    1;

[init]
error	      =    1;
warn	      =    1;
info	      =    1;
proc	      =    1;
dump	      =    1;



